### ISSUE TITLE
【課題】［開発プロセス］現状、どのようなAPIがあるか把握できない

### ISSUE THREAD

**Issue by sis-tomono** [knowledge-board/docs#4]
### 概要
基本はさまざまなサービスを利用して組み立てる、足りないところを補うという方針で進める。
しかし、どのようなAPIがあるか把握する仕組みが現状整備されていない。

### 対応
APIを管理する仕組み、そのプロセスを定義する。
* APIをエンドポイント、メソッド、振る舞いを記載したAPI設計書で管理する。
  * Execelで一覧にまとめる
  * Swaggerをドキュメントとして管理する

### 成果物
* API設計書
  * エンドポイント、メソッド、振る舞い等を明記

**Comment by sis-uchiyama** [comment]
単体プロジェクトの静的APIドキュメント生成の稼動確認完了。
「bootprint」を用いて、起動しているアプリケーションのAPI設計書をドキュメント化。

**Comment by sis-uchiyama** [comment]
## 対応策①
マイクロサービスのAPI Gatewayの役割を果たすプロジェクトを作成し、各アプリケーションのSwagger UIを統合する。

**Comment by sis-uchiyama** [comment]
reference-project-swaggerへ移行
